/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    IconPark: typeof import('./src/components/common/IconPark.vue')['default']
    Menu: typeof import('./src/components/layout/menu/Menu.vue')['default']
    MenuList: typeof import('./src/components/layout/menu/MenuList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
